openapi: 3.1.0
info:
  title: Spotify GPT Agent
  version: 1.0.0
servers:
  - url: https://spottyg.onrender.com

from flask import session, redirect

@app.route("/login")
def login():
    auth_url = sp_oauth.get_authorize_url()
    return redirect(auth_url)

@app.route("/callback")
def callback():
    code = request.args.get('code')
    token_info = sp_oauth.get_access_token(code)
    session["token_info"] = token_info
    return redirect("/")

def get_spotify_client():
    token_info = session.get("token_info")
    if not token_info:
        return redirect("/login")
    if sp_oauth.is_token_expired(token_info):
        token_info = sp_oauth.refresh_access_token(token_info["refresh_token"])
        session["token_info"] = token_info
    return spotipy.Spotify(auth=token_info["access_token"])

sp = get_spotify_client()