openapi: 3.1.0
info:
  title: Spotify GPT Agent
  version: 1.0.0
servers:
  - url: https://spottyg.onrender.com
paths:
  /search_track:
    get:
      operationId: searchTrack
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Track search results
  /search_album:
    get:
      operationId: searchAlbum
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Album search results
  /get_playlists:
    get:
      operationId: getPlaylists
      responses:
        '200':
          description: User playlists
  /create_playlist:
    post:
      operationId: createPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                public:
                  type: boolean
                collaborative:
                  type: boolean
      responses:
        '200':
          description: Playlist created
  /add_to_playlist:
    post:
      operationId: addToPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                playlist_id:
                  type: string
                track_uris:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Tracks added to playlist
components:
  securitySchemes:
    spotifyOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            playlist-read-private: Access private playlists
            playlist-modify-private: Modify private playlists
            playlist-modify-public: Modify public playlists
  schemas: {}
security:
  - spotifyOAuth:
      - playlist-read-private
      - playlist-modify-private
      - playlist-modify-public